<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter your login details_EmailID</name>
   <tag></tag>
   <elementGuidId>d572755b-51ed-4cd4-8b07-57fe55fbaad2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EmailID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EmailID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f231892-fef1-40a2-86f4-3474350f3b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>94b6f49c-5fab-46d8-b82e-69a5431e3d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>74d8e630-1c11-4d48-be7c-3d174a51b815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Enter a valid email address</value>
      <webElementGuid>13d561e5-8774-49a7-8dc6-d84623cd537b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^\s*((([a-zA-Z0-9])+)|([a-zA-Z0-9]+([_\-\.+]?[a-zA-Z0-9])*))[@]((([a-zA-Z0-9])+)|([a-zA-Z0-9]+([_\-\.]?[a-zA-Z0-9])*))[\.][a-zA-Z]{2,}\s*$</value>
      <webElementGuid>120922af-16f5-4a66-8697-c36c292606a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Email address is required</value>
      <webElementGuid>72a14e07-97de-4375-94f2-9c8aa2921b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmailID</value>
      <webElementGuid>57b661c4-b373-458c-8546-58d11f89752a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c2e1cd74-aa6d-4bfe-85b8-355be17eab22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EmailID</value>
      <webElementGuid>3728f2f6-cabd-4938-a1a5-34b96e871c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address</value>
      <webElementGuid>706c66e4-2c47-48c3-a0ee-81aafca0448e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b671ee04-9c9e-41cb-8388-6dcf06ec0bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmailID&quot;)</value>
      <webElementGuid>6a4e8465-05f3-4fd0-82d7-942954b9c598</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EmailID']</value>
      <webElementGuid>dc7e9b7a-74a2-4b6e-b26a-7e7ed7e07be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='VerifyEmailForm']/input</value>
      <webElementGuid>849e1707-9416-488d-bcae-742e88fab765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f818789a-6ce3-47ea-9576-19b5ed52d9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'EmailID' and @name = 'EmailID' and @placeholder = 'Email address' and @type = 'text']</value>
      <webElementGuid>d5a6f07d-96ce-49d4-a2c7-cd762c4abecf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
